# Generated by Django 5.0.6 on 2024-06-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWATH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hp_26695', models.CharField(max_length=100)),
                ('comp_delta', models.FloatField(max_length=200)),
                ('comp_wt', models.FloatField(max_length=200)),
                ('delta_wt', models.FloatField(max_length=200)),
            ],
        ),
    ]
