# Generated by Django 5.0.6 on 2024-06-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glowna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swath',
            options={'ordering': ('Hp_26695',)},
        ),
        migrations.AlterField(
            model_name='swath',
            name='comp_delta',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='swath',
            name='comp_wt',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='swath',
            name='delta_wt',
            field=models.FloatField(max_length=100),
        ),
    ]
